# /etc/calamares/settings.conf
---
modules-search:
  - "/etc/calamares/modules"
  - "/usr/lib/x86_64-linux-gnu/calamares/modules"
  - local

instances:
  - id:       base
    module:   unpackfs
    config:   "/etc/calamares/modules/unpackfs.conf"
  - id:       fixgrub
    module:   grubcfg
    config:   "/etc/calamares/modules/grubcfg.conf"
  - id:       fixboot
    module:   shellprocess
    config:   shellprocess@fixboot.conf  

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - summary
  - exec:
      - partition
      - mount
      - unpackfs@base
      - machineid
      - fstab
      - locale
      - keyboard
      - networkcfg
      - packages
      - luksbootkeyfile      
      - shellprocess@fixboot
      - initramfs
      - grubcfg@fixgrub
      - bootloader
      - umount
  - show:
      - finished

branding: default
prompt-install: false
dont-chroot: false
quit-at-end: false
