# /etc/calamares/settings.conf
---
modules-search:
  - "/usr/lib/x86_64-linux-gnu/calamares/modules"
  - "/etc/calamares/modules"
  - local

instances:
  - id:       base
    module:   unpackfs
    config:   "/etc/calamares/modules/unpackfs.conf"
  - id:       fixgrub
    module:   grubcfg
    config:   "/etc/calamares/modules/grubcfg.conf"

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
#      - users        # FIX: Mandatory for progress bar visibility
      - summary
  - exec:
      - killkeyboard
      - partition
      - mount
      - unpackfs@base
      - machineid
      - fstab
      - locale
      - keyboard
#      - users        # FIX: Mandatory to resolve python-job errors
      - networkcfg
      - initramfs
      - grubcfg@fixgrub
      - bootloader
      - umount
  - show:
      - finished

branding: default
prompt-install: false
dont-chroot: false
quit-at-end: false

