# /etc/calamares/modules/grubcfg.conf 
---
overwrite: true
keep_distributor: true
kernel_params: [ "quiet", "splash" ]

# Default values for GRUB configuration
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DISTRIBUTOR: "Mobian"
    GRUB_TERMINAL_OUTPUT: "gfxterm"
    GRUB_DISABLE_OS_PROBER: "true"
