---
# This is the "Native" way to fix the "No such device" error
overwrite: true
keep_distributor: false
kernel_params: [ "quiet", "splash" ]

# Default values for GRUB configuration
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DISTRIBUTOR: "Mobian"
    GRUB_TERMINAL_OUTPUT: "gfxterm"
    GRUB_DISABLE_OS_PROBER: "false"

