# /etc/calamares/modules/packages.conf
---
backend: apt

update_db: false
update_system: false

# Operations tracking block layout list arrays.
# Using try_install tells Calamares to look inside the local staging system first.
operations:
  - try_install:
      - cryptsetup
      - cryptsetup-initramfs
      - unl0kr
