# etc/calamares/modules/unpackfs.conf
---
unpack:
  - source: "/var/lib/rootfs.sqfs"
    sourcefs: "squashfs"
    destination: ""
    exclude:
      - "/proc/"
      - "/sys/"
      - "/dev/"
      - "/run/"
      - "/run/udev/"
      - "/boot/extlinux"
      # DO NOT ADD "/boot/" HERE! 
      # Leaving "/boot/" out allows vmlinuz and grub to be copied.

