# /etc/calamares/modules/welcome.conf
---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    check:
        - storage
        - ram
    required:
        - storage
        - ram

