[core]
xwayland=true

[output:*]
# Universal wildcard: applies to any detected display
# Forces 1920x1080 resolution with 2x scaling
scale = 1.5

[output:Virtual-1]
# Specific fallback for QXL/Virtualbox drivers
#mode = 1920x1080
scale = 1.5

[output:X11-1]
# Fallback for X11-nested sessions
mode = 1920x1080
scale = 1.5

[output:WL-1]
# Fallback for Wayland-nested sessions
mode = 1920x1080
scale = 1.5

